### ISSUE TITLE
Implementar arquivo [.dev.yml]

### ISSUE THREAD

**Issue by erlimar** [e5r/dev#2]
## Ideia

Os projetos padronizados para o **Time de Desenvolvimento E5R** devem conter um arquivo geral de configurações.
#### `.dev.yml`

``` yaml
project:
  name: my-project
  description: Description of my project
  version: 1.0.2-dev4 #semver.org
  license: MIT, LICENSE.txt

environment:
  python:
    versions:
    - 1.3
      packages:
      - easy_install # $ dev env python -v 1.3 --easy_install --setuptools
    - 2.4
      packages: # $ dev env python -v 2.4 --pip --setuptools
      - pip
    - 3.5.1
      packages:
      - whell
      - pip
    packages:
    - setuptools
  clang:
    versions:
    - 2.5
  node:
    versions:
    - 4.0  # $ dev env node -v 4.0 --npm
    packages:
    - npm

builder:
  python:
    pre:
    - shell command
    build:
    - env build mycommand
    post:
    - shell command
```
### PROJECT

A seção `project` do arquivo guarda as informações gerais do projeto. Com essas informações diversos comandos auxiliares poderão fornecer serviços diversos, de **scaffolding** por exemplo.

Um comando poderia expandir arquivos, de forma que os mesmos teriam variáveis substituídas por valores configurados do projeto.

Ex:

```
$ dev deployer expand config.json
```

Este comando iria transformar um arquivo:

``` json
{
    "application-version": "${project.version}$"
}
```

No seguinte:

``` json
{
    "application-version": "1.0.2-dev4"
}
```

Um outro comando poderia gerar uma tag de versão no **GIT**, ou publicar o projeto no serviço http://nuget.org. A criatividade seria o limite.
### ENVIRONMENT

Na seção `environment` podemos especificar que ambientes são necessários para nosso projeto.

O comando `$ dev env` (issue #1) poderia ser extendido para permitir o `setup` completo do ambiente com base nesse arquivo.

```
$ dev env setup
```

Ou ainda

```
$ dev env setup --workdir ~/path/to/my_project
```

Isso iria instalar todos os ambientes e versões necessárias para a compilação de nosso projeto. Dessa forma um processo de integração/implantação contínua poderia se beneficiar com scripts que somente executaria`$ dev env setup`, ao invés de vários comandos para instalação dos ambientes. Depois em cada tarefa poderia só ativar as versões necessárias.
### BUILDER

A seção `builder` é reservada para automatizar ainda mais o processo de `build` visto que essa é uma tarefa trivial durante o desenvolvimento e que poderia ser iniciada com um simples.

```
$ dev build
```

Ainda poderiamos aplicar filtros:

```
$ dev build --clang
```

Ou ainda:

```
$ dev build --python 1.3
```
## Outras anotações

O arquivo pode conter inúmeras outras seções, como: `deploy`, `publish-artifacts`, `hooks`, etc.

O ponto central é que podemos reunir todas as informações pertinentes aos projetos **E5R Development Team** em um único arquivo, de forma a não causar conflitos com outros arquivos de projeto do tipo `.travis.yml`, `appveyor.yml`, etc.

Ainda poderiamos permitir que a configuração seja desmembrada em vários arquivos, onde o `.dev.yml` podería usar inclusões explícitas:

``` yaml
project: include(.dev/project.yml)
environment:
  python: !import(.env/python.yml)
  node: $imports .env-node.yml
  clang:
    versions:
    - 2.5
builder: !include .dev/env.yml
```
